---
title: "media"
author: "heather"
date: "2024-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# merging the data 
```{r}
media_views = read.csv("data/media_views")
merged_data <- merge(data, media_views, by = "student_id") |>
              select(student_id, dt_started, EOC)

merged_data
```

## Finding average EOCS

```{r}
library(dplyr)
averages <- merged_data %>%
  mutate(video_accessed = ifelse(is.na(dt_started), "No", "Yes")) %>%
  group_by(video_accessed) %>%
  summarise(average_EOC = mean(EOC, na.rm = TRUE))

averages

install.packages("ggplot2")
library(ggplot2)

ggplot(averages, aes(x = video_accessed, y = average_EOC, fill = video_accessed)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.5) + # Adjusted width here
  theme_minimal() +
  labs(title = "Average EOC Scores by Video Access",
       x = "Video Accessed",
       y = "Average EOC Score") +
  scale_fill_manual(values = c("Yes" = "blue", "No" = "red")) +
  geom_text(aes(label = round(average_EOC, 2)), vjust = -0.5, color = "black")

```
# EOC average of those who watched the video (proportion_video >= 0.5)
```{r}
averages_watched <- merged_data %>%
  mutate(video_watched = ifelse((proportion_video >= 0.5), "No", "Yes")) %>%
  group_by(video_watched) %>%
  summarise(average_EOC = mean(EOC, na.rm = TRUE))

averages

